# Generated by Django 5.1.1 on 2024-09-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_tiltle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tiltle',
            new_name='Title',
        ),
    ]
