# Generated by Django 5.1.1 on 2024-09-25 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_title_description_title_sold_title_type_title_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
