# Generated by Django 5.1.1 on 2024-09-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_title_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='like_new',
            field=models.BooleanField(default=True),
        ),
    ]
